# Generated by Django 5.1.1 on 2024-10-07 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_reportage', models.ImageField(upload_to='goal_report/')),
                ('video_reportage', models.FileField(blank=True, null=True, upload_to='goal_video/')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.goal')),
            ],
        ),
    ]
