# Generated by Django 5.1.1 on 2024-10-06 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reportactive_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportactive',
            old_name='date_created',
            new_name='date_reported',
        ),
        migrations.AddField(
            model_name='reportactive',
            name='description',
            field=models.TextField(default='Dummy report'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.goal')),
            ],
        ),
    ]
